### ISSUE TITLE
Good Example link is broken.

### ISSUE THREAD

**Issue by v-xecamp** [doudou/flexmock#13]
It would probably help many if this was available.

**Comment by doudou** [comment]
Could you be more specific ? What link are you talking about ?

**Comment by olleolleolle** [comment]
The only broken link I can find would be the rubyforge reference in https://github.com/doudou/flexmock/blob/master/doc/index.rdoc

**Comment by doudou** [comment]
@v-xecamp I'm closing this ... without you pointing where there's a broken link, I'm afraid there isn't much I can do...

**Comment by doudou** [comment]
(and @olleolleolle thanks for the info, it's fixed now)
