### ISSUE TITLE
License file?

### ISSUE THREAD

**Issue by junaruga** [doudou/flexmock#6]
I saw this package was MIT license in `flexmock.gemspec` file.
Is it possible to include License file to your next version gem file?
Github has good feature to support having license.
Also see: https://github.com/jimweirich/flexmock/issues/23 (I mistook the repo to report the issue).

**Comment by junaruga** [comment]
Here is a help page to add License file from Github UI.
https://help.github.com/articles/licensing-a-repository/

**Comment by doudou** [comment]
Done ... I did not know about the magic-add-LICENSE feature of github. Pretty cool ...

**Comment by junaruga** [comment]
@doudou Yeah, it's cool feature. Thanks!
