### ISSUE TITLE
FlexMock::Undefined when attempting to use minitest-hooks or share flexmock instances between test cases

### ISSUE THREAD

**Issue by erose** [doudou/flexmock#8]
Thank you for maintaining this gem!

Now, the problem. Here is a minimal example. (using https://github.com/jeremyevans/minitest-hooks)

```
require 'minitest/autorun'
require 'flexmock/minitest'
require 'minitest/hooks/default'

class A
  def foo
    'hi'
  end
end

class SimpleTest < Minitest::Test
  include Minitest::Hooks

  def around_all
    A.stub(:new, flexmock(foo: 'bye')) do
      super
    end
  end

  def test_it_once
    puts A.new.foo
  end

  def test_it_twice
    puts A.new.foo
  end
end
```

Running this file produces `TypeError: can't convert FlexMock::Undefined to Array`.

From skimming the code, it looks like the teardown logic for `test_it_once` is "closing" the flexmock instance, putting it in a state where it respondes `FlexMock::Undefined` to all messages.

I also saw the same error in another case, without minitest-hooks, where a caching scheme in the tested code was causing the flexmock instance to be shared between two test cases.

Two questions:
  * Is it possible to do "stub out `A` with this mock object for all test cases in this file" using flexmock? What would you recommend?
  * Are flexmock instances intended never to be shared between test cases by design?

**Comment by doudou** [comment]
> Are flexmock instances intended never to be shared between test cases by design?

Yes and no. The `#flexmock` helper is actually designed to be "closed down and validated" on teardown. This can't be helped, it's really how the whole flexmock-test integration works. Without that, one would not get e.g. "meant to be called once but got zero calls" errors when a test finishes.

You could however create a mock that is not bound to the test by manually creating a container.

~~~
def around_all
  container = FlexMock::UseContainer.new
  A.stub(:new, container.flexmock(foo: 'bye')) do
    super
  end
ensure
  container.flexmock_teardown
end
~~~

I guess that there might be a way to have a cleaner integration with around_all... However I'm not using minitest-hooks myself, and I don't really have the time to dig into that.

**Comment by erose** [comment]
Thanks for your response @doudou! I'm thinking that flexmock is not really designed for my use case.
